import torch
import torch.nn.functional as F
from transformers import AutoTokenizer, AutoModel

# Load a small BERT model directly via transformers to bypass Windows Application Control DLL errors in scikit-learn/scipy
model_name = 'sentence-transformers/all-MiniLM-L6-v2'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

# Mean Pooling - Take attention mask into account for correct averaging
def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0] # First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)

# Standard OCSF categories and their descriptions to match against
OCSF_CATEGORIES = {
    "Network Activity": "Logs related to network traffic, network connections, firewall rules, and IP routing (e.g., src, dst, TCP, UDP).",
    "Authentication": "Logs related to user login, logout, authentication failures, and access control.",
    "Process Activity": "Logs related to process creation, process termination, and execution on a host.",
    "File System Activity": "Logs related to file creation, modification, deletion, and permission changes.",
    "Security Finding": "Logs generated by security tools indicating a threat, malware, or vulnerability."
}

category_names = list(OCSF_CATEGORIES.keys())
category_descriptions = list(OCSF_CATEGORIES.values())

def get_embeddings(sentences):
    # Tokenize sentences
    encoded_input = tokenizer(sentences, padding=True, truncation=True, return_tensors='pt')
    
    # Compute token embeddings
    with torch.no_grad():
        model_output = model(**encoded_input)
        
    # Perform pooling and normalize
    sentence_embeddings = mean_pooling(model_output, encoded_input['attention_mask'])
    return F.normalize(sentence_embeddings, p=2, dim=1)

# Pre-compute embeddings for the categories
category_embeddings = get_embeddings(category_descriptions)

def classify_template(template: str) -> tuple[str, float]:
    """
    Classify a log template into an OCSF category using a small BERT embedding model.
    """
    # Embed the log template
    template_embedding = get_embeddings([template])
    
    # Compute cosine similarities between the template and OCSF categories
    cosine_scores = F.cosine_similarity(template_embedding, category_embeddings)
    
    # Find the best matching category
    best_match_index = torch.argmax(cosine_scores).item()
    confidence = cosine_scores[best_match_index].item()
    return category_names[best_match_index], confidence
